export const upcomingTours = [
  {
    city: "Milan, Italy",
    date: "2025-11-05",
    place: "Teatro degli Arcimboldi",
    time: "20:00",
    cityImage: "/images/tours/milan.jpg",
  },
  {
    city: "Paris, France",
    date: "2025-11-12",
    place: "Philharmonie de Paris",
    time: "19:30",
    cityImage: "/images/tours/paris.jpg",
  },
  {
    city: "London, UK",
    date: "2025-11-18",
    place: "Royal Albert Hall",
    time: "20:00",
    cityImage: "/images/tours/london.jpg",
  },
  {
    city: "Berlin, Germany",
    date: "2025-11-25",
    place: "Konzerthaus Berlin",
    time: "19:00",
    cityImage: "/images/tours/berlin.jpg",
  },
  {
    city: "Zurich, Switzerland",
    date: "2025-12-01",
    place: "Tonhalle Zürich",
    time: "20:00",
    cityImage: "/images/tours/zurich.jpg",
  },
  {
    city: "Amsterdam, Netherlands",
    date: "2025-12-08",
    place: "Concertgebouw Amsterdam",
    time: "20:30",
    cityImage: "/images/tours/amsterdam.jpg",
  },
  {
    city: "New York, USA",
    date: "2026-01-10",
    place: "Carnegie Hall",
    time: "19:30",
    cityImage: "/images/tours/newyork.jpg",
  },
  {
    city: "Toronto, Canada",
    date: "2026-01-15",
    place: "Roy Thomson Hall",
    time: "20:00",
    cityImage: "/images/tours/toronto.jpg",
  },
  {
    city: "Tokyo, Japan",
    date: "2026-02-05",
    place: "Tokyo International Forum",
    time: "19:00",
    cityImage: "/images/tours/tokyo.jpg",
  },
  {
    city: "Sydney, Australia",
    date: "2026-02-20",
    place: "Sydney Opera House",
    time: "20:00",
    cityImage: "/images/tours/sydney.jpg",
  },
];